### ISSUE TITLE
make up .env file syntax

### ISSUE THREAD

**Issue by f1ght3r** [angelo-v/wordpress-backup-quickstart#1]
make script writes in the .env file "-e 'name=value' ..." when docker expects just "name=value" without the preceding -e (used when starting container from cli without a env file).

**Comment by angelo-v** [comment]
Cannot reproduce. `-e` is an argument of the `echo` command and is *not* written to the output.

If you experience otherwise, please provide details about your system / OS.

**Comment by angelo-v** [comment]
Could reproduce it on another OS and removed it
